# available themes: minimal, cayman, hacker, architect, midnight, slate, primer, dinky, modernist, leap-day, time-machine, merlot, tactile
# theme: jekyll-theme-cayman
# theme: jekyll-theme-time-machine
theme: jekyll-theme-modernist
# title: Mohd.Hasanudin bin Zakaria - Senior Application Developer
description: Professional Portfolio & Resume
